// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AccountsCreateData,
  AccountsCreateResponses,
  AccountsFindAllData,
  AccountsFindAllResponses,
  AccountsFindOneData,
  AccountsFindOneResponses,
  AccountsGetBalanceData,
  AccountsGetBalanceResponses,
  AccountsRemoveData,
  AccountsRemoveResponses,
  AccountsUpdateData,
  AccountsUpdateResponses,
  AuthLoginData,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutResponses,
  AuthMeData,
  AuthMeResponses,
  AuthRefreshData,
  AuthRefreshResponses,
  AuthRegisterData,
  AuthRegisterResponses,
  CategoriesCreateData,
  CategoriesCreateResponses,
  CategoriesFindAllData,
  CategoriesFindAllResponses,
  CategoriesFindOneData,
  CategoriesFindOneResponses,
  CategoriesRemoveData,
  CategoriesRemoveResponses,
  CategoriesUpdateData,
  CategoriesUpdateResponses,
  HealthCheckData,
  HealthCheckResponses,
  MerchantsCreateData,
  MerchantsCreateResponses,
  MerchantsFindAllData,
  MerchantsFindAllResponses,
  MerchantsFindOneData,
  MerchantsFindOneResponses,
  MerchantsRemoveData,
  MerchantsRemoveResponses,
  MerchantsUpdateData,
  MerchantsUpdateResponses,
  ProductsCreateData,
  ProductsCreateResponses,
  ProductsFindAllData,
  ProductsFindAllResponses,
  ProductsFindOneData,
  ProductsFindOneResponses,
  ProductsRemoveData,
  ProductsRemoveResponses,
  ProductsUpdateData,
  ProductsUpdateResponses,
  ReceiptsCreateData,
  ReceiptsCreateResponses,
  ReceiptsScanData,
  ReceiptsScanResponses,
  ReimbursementsFindOutstandingData,
  ReimbursementsFindOutstandingResponses,
  TransactionItemsCreateData,
  TransactionItemsCreateResponses,
  TransactionItemsRemoveData,
  TransactionItemsRemoveResponses,
  TransactionItemsUpdateData,
  TransactionItemsUpdateResponses,
  TransactionsCreateData,
  TransactionsCreateResponses,
  TransactionSettlementsSettleData,
  TransactionSettlementsSettleResponses,
  TransactionSettlementsUnsettleData,
  TransactionSettlementsUnsettleResponses,
  TransactionsFindAllData,
  TransactionsFindAllResponses,
  TransactionsFindOneData,
  TransactionsFindOneResponses,
  TransactionsRemoveData,
  TransactionsRemoveResponses,
  TransactionsSummariseData,
  TransactionsSummariseResponses,
  TransactionsUpdateData,
  TransactionsUpdateResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create an account. Requires the shared invite code.
 */
export const authRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthRegisterData, ThrowOnError>,
): RequestResult<AuthRegisterResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AuthRegisterResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Exchange username and password for a token pair.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
): RequestResult<AuthLoginResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AuthLoginResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Rotate a refresh token for a fresh pair.
 */
export const authRefresh = <ThrowOnError extends boolean = false>(
  options: Options<AuthRefreshData, ThrowOnError>,
): RequestResult<AuthRefreshResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AuthRefreshResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Revoke a refresh token.
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options: Options<AuthLogoutData, ThrowOnError>,
): RequestResult<AuthLogoutResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({
    url: '/auth/logout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * The signed-in user.
 */
export const authMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthMeData, ThrowOnError>,
): RequestResult<AuthMeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AuthMeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options,
  });

/**
 * Liveness probe that also round-trips the database.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>,
): RequestResult<HealthCheckResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options,
  });

/**
 * List accounts, each carrying its balance, with totals per currency.
 */
export const accountsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<AccountsFindAllData, ThrowOnError>,
): RequestResult<AccountsFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AccountsFindAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts',
    ...options,
  });

/**
 * Create an account.
 */
export const accountsCreate = <ThrowOnError extends boolean = false>(
  options: Options<AccountsCreateData, ThrowOnError>,
): RequestResult<AccountsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AccountsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete an account and every transaction on it.
 */
export const accountsRemove = <ThrowOnError extends boolean = false>(
  options: Options<AccountsRemoveData, ThrowOnError>,
): RequestResult<AccountsRemoveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<AccountsRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts/{id}',
    ...options,
  });

/**
 * Fetch a single account.
 */
export const accountsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<AccountsFindOneData, ThrowOnError>,
): RequestResult<AccountsFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<AccountsFindOneResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts/{id}',
    ...options,
  });

/**
 * Update, archive or restore an account.
 */
export const accountsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AccountsUpdateData, ThrowOnError>,
): RequestResult<AccountsUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<AccountsUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Current balance, derived from the opening balance and transactions.
 */
export const accountsGetBalance = <ThrowOnError extends boolean = false>(
  options: Options<AccountsGetBalanceData, ThrowOnError>,
): RequestResult<AccountsGetBalanceResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<AccountsGetBalanceResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts/{id}/balance',
    ...options,
  });

/**
 * List categories, optionally filtered by kind and account.
 */
export const categoriesFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CategoriesFindAllData, ThrowOnError>,
): RequestResult<CategoriesFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<CategoriesFindAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories',
    ...options,
  });

/**
 * Create a category.
 */
export const categoriesCreate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesCreateData, ThrowOnError>,
): RequestResult<CategoriesCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CategoriesCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a category; its transactions stay, uncategorised.
 */
export const categoriesRemove = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesRemoveData, ThrowOnError>,
): RequestResult<CategoriesRemoveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<CategoriesRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories/{id}',
    ...options,
  });

/**
 * Fetch a single category.
 */
export const categoriesFindOne = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesFindOneData, ThrowOnError>,
): RequestResult<CategoriesFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<CategoriesFindOneResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories/{id}',
    ...options,
  });

/**
 * Update a category.
 */
export const categoriesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesUpdateData, ThrowOnError>,
): RequestResult<CategoriesUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<CategoriesUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List merchants, optionally filtered by name.
 */
export const merchantsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<MerchantsFindAllData, ThrowOnError>,
): RequestResult<MerchantsFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<MerchantsFindAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/merchants',
    ...options,
  });

/**
 * Create a merchant.
 */
export const merchantsCreate = <ThrowOnError extends boolean = false>(
  options: Options<MerchantsCreateData, ThrowOnError>,
): RequestResult<MerchantsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<MerchantsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/merchants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a merchant; its transactions stay, with no merchant.
 */
export const merchantsRemove = <ThrowOnError extends boolean = false>(
  options: Options<MerchantsRemoveData, ThrowOnError>,
): RequestResult<MerchantsRemoveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<MerchantsRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/merchants/{id}',
    ...options,
  });

/**
 * Fetch a single merchant.
 */
export const merchantsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<MerchantsFindOneData, ThrowOnError>,
): RequestResult<MerchantsFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<MerchantsFindOneResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/merchants/{id}',
    ...options,
  });

/**
 * Rename a merchant.
 */
export const merchantsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<MerchantsUpdateData, ThrowOnError>,
): RequestResult<MerchantsUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<MerchantsUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/merchants/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List products, optionally scoped to one merchant.
 */
export const productsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<ProductsFindAllData, ThrowOnError>,
): RequestResult<ProductsFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ProductsFindAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/products',
    ...options,
  });

/**
 * Create a product under a merchant.
 */
export const productsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsCreateData, ThrowOnError>,
): RequestResult<ProductsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<ProductsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/products',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a product.
 */
export const productsRemove = <ThrowOnError extends boolean = false>(
  options: Options<ProductsRemoveData, ThrowOnError>,
): RequestResult<ProductsRemoveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<ProductsRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/products/{id}',
    ...options,
  });

/**
 * Fetch a single product.
 */
export const productsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<ProductsFindOneData, ThrowOnError>,
): RequestResult<ProductsFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<ProductsFindOneResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/products/{id}',
    ...options,
  });

/**
 * Update a product.
 */
export const productsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProductsUpdateData, ThrowOnError>,
): RequestResult<ProductsUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<ProductsUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/products/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List transactions, newest first.
 */
export const transactionsFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsFindAllData, ThrowOnError>,
): RequestResult<TransactionsFindAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TransactionsFindAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions',
    ...options,
  });

/**
 * Record a transaction. Currency is inherited from the account.
 */
export const transactionsCreate = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsCreateData, ThrowOnError>,
): RequestResult<TransactionsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<TransactionsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Income/expense totals and per-category breakdown for a window.
 */
export const transactionsSummarise = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsSummariseData, ThrowOnError>,
): RequestResult<TransactionsSummariseResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TransactionsSummariseResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/summary',
    ...options,
  });

/**
 * Delete a transaction.
 */
export const transactionsRemove = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsRemoveData, ThrowOnError>,
): RequestResult<TransactionsRemoveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<TransactionsRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/{id}',
    ...options,
  });

/**
 * Fetch a single transaction.
 */
export const transactionsFindOne = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsFindOneData, ThrowOnError>,
): RequestResult<TransactionsFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<TransactionsFindOneResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/{id}',
    ...options,
  });

/**
 * Update a transaction.
 */
export const transactionsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsUpdateData, ThrowOnError>,
): RequestResult<TransactionsUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<TransactionsUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Add a line to a receipt. Returns the transaction with its new total.
 */
export const transactionItemsCreate = <ThrowOnError extends boolean = false>(
  options: Options<TransactionItemsCreateData, ThrowOnError>,
): RequestResult<TransactionItemsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<TransactionItemsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/{transactionId}/items',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove one line. Returns the transaction with its new total.
 */
export const transactionItemsRemove = <ThrowOnError extends boolean = false>(
  options: Options<TransactionItemsRemoveData, ThrowOnError>,
): RequestResult<TransactionItemsRemoveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<TransactionItemsRemoveResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/{transactionId}/items/{itemId}',
    ...options,
  });

/**
 * Edit one line. Returns the transaction with its new total.
 */
export const transactionItemsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TransactionItemsUpdateData, ThrowOnError>,
): RequestResult<TransactionItemsUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<TransactionItemsUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/{transactionId}/items/{itemId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Record that a wallet paid back its share of this receipt. Settles the whole of what it currently owes and posts both sides of the money.
 */
export const transactionSettlementsSettle = <ThrowOnError extends boolean = false>(
  options: Options<TransactionSettlementsSettleData, ThrowOnError>,
): RequestResult<TransactionSettlementsSettleResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<TransactionSettlementsSettleResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions/{transactionId}/settlements',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Undo a settlement, removing both transactions it posted.
 */
export const transactionSettlementsUnsettle = <ThrowOnError extends boolean = false>(
  options: Options<TransactionSettlementsUnsettleData, ThrowOnError>,
): RequestResult<TransactionSettlementsUnsettleResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<TransactionSettlementsUnsettleResponses, unknown, ThrowOnError>(
    {
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/transactions/{transactionId}/settlements/{owedAccountId}',
      ...options,
    },
  );

/**
 * Every share still owed from one wallet to another, rolled up per pair of wallets and largest first.
 */
export const reimbursementsFindOutstanding = <ThrowOnError extends boolean = false>(
  options?: Options<ReimbursementsFindOutstandingData, ThrowOnError>,
): RequestResult<ReimbursementsFindOutstandingResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ReimbursementsFindOutstandingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/reimbursements/outstanding',
    ...options,
  });

/**
 * Read a receipt photo into a draft. Writes nothing.
 *
 * Extracts the merchant, date, lines and charges, resolves them against the catalogue, and returns both the printed total and the derived one so the reviewer can see whether anything was misread.
 */
export const receiptsScan = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsScanData, ThrowOnError>,
): RequestResult<ReceiptsScanResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<ReceiptsScanResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/receipts/scan',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create an expense with all its lines and charges in one atomic write.
 */
export const receiptsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsCreateData, ThrowOnError>,
): RequestResult<ReceiptsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<ReceiptsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/receipts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
