// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type RegisterDto = {
  username: string;
  /**
   * Stored only as an argon2 hash.
   */
  password: string;
  displayName?: string;
  /**
   * Shared invite code. Registration is closed without it.
   */
  inviteCode: string;
};

export type UserResponse = {
  id: string;
  username: string;
  displayName?: string | null;
  createdAt: string;
};

export type AuthTokensResponse = {
  /**
   * Short-lived bearer token for the Authorization header.
   */
  accessToken: string;
  /**
   * Opaque token, exchanged at /auth/refresh. Rotated on every use.
   */
  refreshToken: string;
  /**
   * Seconds until the access token expires.
   */
  expiresIn: number;
  user: UserResponse;
};

export type LoginDto = {
  username: string;
  password: string;
};

export type RefreshDto = {
  /**
   * The refresh token from the last token response.
   */
  refreshToken: string;
};

export type HealthResponse = {
  status: 'ok' | 'degraded';
  database: 'up' | 'down';
  /**
   * Process uptime in seconds.
   */
  uptime: number;
};

export const AccountType = {
  CASH: 'CASH',
  BANK: 'BANK',
  EWALLET: 'EWALLET',
  CREDIT_CARD: 'CREDIT_CARD',
  INVESTMENT: 'INVESTMENT',
} as const;

export type AccountType = (typeof AccountType)[keyof typeof AccountType];

export type AccountBalanceResponse = {
  accountId: string;
  currency: string;
  openingBalanceMinor: number;
  incomeMinor: number;
  expenseMinor: number;
  /**
   * openingBalanceMinor + incomeMinor - expenseMinor
   */
  balanceMinor: number;
};

export type AccountResponse = {
  id: string;
  name: string;
  type: AccountType;
  /**
   * ISO 4217 code.
   */
  currency: string;
  openingBalanceMinor: number;
  /**
   * Carried on every account so a list renders its balances without a request
   * per row. Identical to what `GET /accounts/:id/balance` returns.
   */
  balance: AccountBalanceResponse;
  /**
   * Categories paid from this account. Deleting it leaves them unassigned.
   */
  categoryCount: number;
  /**
   * Transactions posted here. Deleting the account deletes them.
   */
  transactionCount: number;
  archivedAt?: string | null;
  createdAt: string;
  updatedAt: string;
};

export type AccountCurrencyTotalResponse = {
  /**
   * ISO 4217 code.
   */
  currency: string;
  /**
   * Integer minor units of `currency`.
   */
  totalMinor: number;
  /**
   * Accounts denominated in this currency.
   */
  accountCount: number;
};

export type PaginatedAccountsResponse = {
  /**
   * Total rows matching the filter, ignoring limit/offset.
   */
  total: number;
  limit: number;
  offset: number;
  data: Array<AccountResponse>;
  /**
   * Rolled up over the whole filtered set, not the page.
   *
   * Net worth has to stay correct while the list is paged, so the client can
   * never derive it by folding `data` — past the first page that would silently
   * under-count. Ordered by `totalMinor`, largest first.
   */
  totalsByCurrency: Array<AccountCurrencyTotalResponse>;
  /**
   * Archived accounts matching `search`, counted whether or not
   * `includeArchived` is set — it is what labels the "show archived" toggle,
   * which has to know the count *before* it is switched on.
   */
  archivedTotal: number;
};

export type CreateAccountDto = {
  name: string;
  type: AccountType;
  /**
   * ISO 4217 code.
   */
  currency?: string;
  /**
   * Balance before the first tracked transaction, in minor units.
   */
  openingBalanceMinor?: number;
};

export type UpdateAccountDto = {
  name?: string;
  type?: AccountType;
  /**
   * ISO 4217 code.
   */
  currency?: string;
  /**
   * Balance before the first tracked transaction, in minor units.
   */
  openingBalanceMinor?: number;
  /**
   * Archive (true) or restore (false) the account.
   */
  archived?: boolean;
};

export const CategoryKind = { INCOME: 'INCOME', EXPENSE: 'EXPENSE' } as const;

export type CategoryKind = (typeof CategoryKind)[keyof typeof CategoryKind];

export type CategoryResponse = {
  id: string;
  name: string;
  /**
   * The account this category is paid from; null when it is unassigned.
   */
  accountId?: string | null;
  /**
   * Denormalised so a category list need not also fetch accounts.
   */
  accountName?: string | null;
  kind: CategoryKind;
  color?: string | null;
  /**
   * Receipt lines filed under this category. Deleting it leaves them uncategorised.
   */
  transactionItemCount: number;
  /**
   * Catalogue products classified by this category.
   */
  productCount: number;
  createdAt: string;
  updatedAt: string;
};

export type CreateCategoryDto = {
  name: string;
  /**
   * The account this category is paid from. Optional — an unassigned category can
   * be used on any account.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  accountId?: string | null;
  kind: CategoryKind;
  /**
   * Hex swatch used by the UI.
   */
  color?: string;
};

export type UpdateCategoryDto = {
  name?: string;
  /**
   * The account this category is paid from. Optional — an unassigned category can
   * be used on any account.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  accountId?: string | null;
  kind?: CategoryKind;
  /**
   * Hex swatch used by the UI.
   */
  color?: string;
};

export type MerchantResponse = {
  id: string;
  name: string;
  /**
   * How many transactions point at this merchant. Deleting it detaches them, not deletes them.
   */
  transactionCount: number;
  /**
   * How many products this merchant sells. Deleting it deletes them too.
   */
  productCount: number;
  createdAt: string;
  updatedAt: string;
};

export type CreateMerchantDto = {
  name: string;
};

export type UpdateMerchantDto = {
  name?: string;
};

export type CategorySummaryResponse = {
  id: string;
  name: string;
  kind: CategoryKind;
  color?: string | null;
};

export type ProductResponse = {
  id: string;
  merchantId: string;
  /**
   * Denormalised so a product list need not also fetch merchants.
   */
  merchantName: string;
  /**
   * Only null for rows that predate categorised products.
   */
  category?: CategorySummaryResponse | null;
  /**
   * Null when the shop prints no code for this.
   */
  code?: string | null;
  name: string;
  /**
   * Price last paid, in minor units of `currency`.
   */
  lastPriceMinor: number;
  /**
   * ISO 4217 code. Always IDR for now.
   */
  currency: string;
  createdAt: string;
  updatedAt: string;
};

export type CreateProductDto = {
  /**
   * The merchant that sells this product.
   */
  merchantId: string;
  /**
   * Must be an EXPENSE category.
   */
  categoryId: string;
  /**
   * The merchant's own SKU, unique within that merchant. Optional: plenty of
   * things you buy have no printed code, and an empty string clears one that
   * was set rather than storing a blank.
   */
  code?: string;
  name: string;
  /**
   * Price last paid, in IDR minor units.
   */
  lastPriceMinor: number;
};

export type UpdateProductDto = {
  /**
   * The merchant that sells this product.
   */
  merchantId?: string;
  /**
   * Must be an EXPENSE category.
   */
  categoryId?: string;
  /**
   * The merchant's own SKU, unique within that merchant. Optional: plenty of
   * things you buy have no printed code, and an empty string clears one that
   * was set rather than storing a blank.
   */
  code?: string;
  name?: string;
  /**
   * Price last paid, in IDR minor units.
   */
  lastPriceMinor?: number;
};

export const TransactionType = { INCOME: 'INCOME', EXPENSE: 'EXPENSE' } as const;

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType];

export type TransactionAccountResponse = {
  id: string;
  name: string;
  type: AccountType;
};

export type TransactionMerchantResponse = {
  id: string;
  name: string;
};

export type TransactionItemDiscountResponse = {
  id: string;
  name?: string | null;
  /**
   * Basis points off the running remainder (5% is 500). Null for a typed lump sum.
   */
  basisPoints?: number | null;
  /**
   * What this row came to, in minor units.
   */
  amountMinor: number;
  /**
   * Order on the line, which is the order the cascade applies in.
   */
  position: number;
};

export type TransactionItemProductResponse = {
  id: string;
  code?: string | null;
  name: string;
};

export type TransactionItemResponse = {
  id: string;
  name: string;
  quantity: number;
  unitPriceMinor: number;
  /**
   * Every discount off this line, in the order they cascade.
   */
  discounts: Array<TransactionItemDiscountResponse>;
  /**
   * What the whole cascade comes to as one rate (24% is 2400), derived by the API. Zero when nothing was discounted.
   */
  discountBasisPoints: number;
  /**
   * The sum of `discounts`, derived by the API.
   */
  discountMinor: number;
  /**
   * quantity × unitPriceMinor − discountMinor.
   */
  lineTotalMinor: number;
  /**
   * Order on the receipt.
   */
  position: number;
  /**
   * Null for a line typed by hand that is not in the catalogue.
   */
  product?: TransactionItemProductResponse | null;
  /**
   * Only null for rows that predate categorised lines.
   */
  category?: CategorySummaryResponse | null;
  createdAt: string;
  updatedAt: string;
};

export type TransactionChargeResponse = {
  id: string;
  name: string;
  /**
   * Basis points (11% is 1100). Null when the amount was typed directly.
   */
  percentBasisPoints?: number | null;
  amountMinor: number;
  /**
   * Order on the receipt.
   */
  position: number;
  createdAt: string;
  updatedAt: string;
};

export type TransactionSplitLineResponse = {
  category: CategorySummaryResponse;
  /**
   * The account this category is paid from.
   */
  accountId: string;
  /**
   * Denormalised so the split need not also fetch accounts.
   */
  accountName: string;
  /**
   * Sum of the lines filed under this category, in minor units.
   */
  itemsMinor: number;
  /**
   * This category's share of the receipt's additional charges, prorated by `itemsMinor`.
   */
  chargeShareMinor: number;
  /**
   * `itemsMinor` + `chargeShareMinor`.
   */
  owedMinor: number;
};

export type TransactionSettlementResponse = {
  id: string;
  /**
   * What was owed at the moment it was settled, in minor units.
   */
  settledMinor: number;
  settledAt: string;
  /**
   * The INCOME posted to the account that fronted the receipt.
   */
  inboundTransactionId?: string | null;
  /**
   * The EXPENSE posted to the account that owed the share.
   */
  outboundTransactionId?: string | null;
  /**
   * True when the receipt has been edited since, so what is owed now no longer matches what was paid back. Nothing is corrected automatically — the difference is the user's to settle or ignore.
   */
  isStale: boolean;
};

export type TransactionSplitDebtorResponse = {
  accountId: string;
  accountName: string;
  /**
   * What this wallet owes as the receipt currently stands, in minor units. Recomputed on every read, so it moves when the receipt is edited — including after it was settled.
   */
  owedMinor: number;
  /**
   * Null while the share is still outstanding.
   */
  settlement?: TransactionSettlementResponse | null;
};

export type TransactionSplitResponse = {
  /**
   * The paying account's own share: lines whose category is linked to it, or to no account at all, plus its prorated part of the charges. An uncategorised line, or one under an unassigned category, cannot be attributed to anyone else and stays here.
   */
  ownShareMinor: number;
  /**
   * One row per category owed to another wallet, largest first. What the figures are made of.
   */
  lines: Array<TransactionSplitLineResponse>;
  /**
   * `lines` rolled up per wallet, largest first. Who owes, and what has been settled.
   */
  debtors: Array<TransactionSplitDebtorResponse>;
};

export type TransactionResponse = {
  id: string;
  type: TransactionType;
  /**
   * Positive integer in minor units; sign comes from `type`. On an EXPENSE it is derived — the sum of `items[].lineTotalMinor` plus `charges[].amountMinor`, so a receipt with nothing on it yet reads zero. On an INCOME it is the figure that was entered, and there are neither items nor charges.
   */
  amountMinor: number;
  currency: string;
  occurredAt: string;
  description?: string | null;
  notes?: string | null;
  account: TransactionAccountResponse;
  merchant?: TransactionMerchantResponse | null;
  /**
   * How an INCOME transaction is classified, since it has no items to carry a category. Always null on an EXPENSE, which is categorised line by line in `items[].category`.
   */
  category?: CategorySummaryResponse | null;
  /**
   * What was bought, in receipt order. Empty until an expense is itemised, and always empty on income — the API refuses to write items on an INCOME transaction.
   */
  items: Array<TransactionItemResponse>;
  /**
   * Tax, service charge and the like — money paid on top of what was bought, in receipt order. Counts towards `amountMinor` but carries no category, so it is absent from the summary's per-category breakdown. Always empty on income.
   */
  charges: Array<TransactionChargeResponse>;
  /**
   * How this receipt divides between the account that paid it and accounts it was partly paid for — derived from each line's category and the account that category is linked to. Null when nothing is owed to anyone else, and on every income row.
   */
  split?: TransactionSplitResponse | null;
  /**
   * True when this row was posted by settling a split rather than entered by hand. Such a row is not editable: its amount is authoritative, and the API refuses every write to it so the expense recompute can never reach it. Undo it by unsettling instead.
   */
  isSettlement: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PaginatedTransactionsResponse = {
  /**
   * Total rows matching the filter, ignoring limit/offset.
   */
  total: number;
  limit: number;
  offset: number;
  data: Array<TransactionResponse>;
};

export type CategoryTotalResponse = {
  categoryId?: string | null;
  categoryName: string;
  color?: string | null;
  type: TransactionType;
  totalMinor: number;
};

export type TransactionsSummaryResponse = {
  from: string;
  to: string;
  incomeMinor: number;
  expenseMinor: number;
  /**
   * incomeMinor - expenseMinor
   */
  netMinor: number;
  byCategory: Array<CategoryTotalResponse>;
};

export type CreateTransactionChargeDto = {
  name: string;
  /**
   * Basis points (11% is 1100). The percentage that produced `amountMinor`, if any.
   */
  percentBasisPoints?: number | null;
  /**
   * What the charge came to, in minor units of the transaction's currency.
   */
  amountMinor: number;
};

export type CreateTransactionDto = {
  accountId: string;
  /**
   * Optional. A transaction with no merchant is perfectly valid.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  merchantId?: string | null;
  type: TransactionType;
  /**
   * Required on INCOME, rejected on EXPENSE. Minor units of the account's currency.
   */
  amountMinor?: number;
  /**
   * Required on INCOME and must be an INCOME category. Rejected on EXPENSE.
   */
  categoryId?: string | null;
  occurredAt: string;
  description?: string;
  notes?: string;
  /**
   * EXPENSE only. Replaces every existing charge; `[]` clears them, absent leaves them alone.
   */
  charges?: Array<CreateTransactionChargeDto>;
};

export type UpdateTransactionDto = {
  accountId?: string;
  /**
   * Optional. A transaction with no merchant is perfectly valid.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  merchantId?: string | null;
  type?: TransactionType;
  /**
   * Required on INCOME, rejected on EXPENSE. Minor units of the account's currency.
   */
  amountMinor?: number;
  /**
   * Required on INCOME and must be an INCOME category. Rejected on EXPENSE.
   */
  categoryId?: string | null;
  occurredAt?: string;
  description?: string;
  notes?: string;
  /**
   * EXPENSE only. Replaces every existing charge; `[]` clears them, absent leaves them alone.
   */
  charges?: Array<CreateTransactionChargeDto>;
};

export type TransactionItemDiscountDto = {
  /**
   * As printed. Null when the receipt only prints a figure.
   */
  name?: string | null;
  /**
   * Basis points off what is left at this point in the cascade (20% is 2000). The API derives the money from it. Omit when giving an amount instead.
   */
  basisPoints?: number | null;
  /**
   * A lump sum off the line — a voucher — in minor units. Unaffected by the quantity. Omit when giving a rate instead.
   */
  amountMinor?: number | null;
};

export type CreateTransactionItemDto = {
  /**
   * Optional link to the catalogue. A line typed by hand has none and needs no
   * product code at all — promoting it to master data is a separate, deliberate step.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  productId?: string | null;
  /**
   * Required, unlike the product link: every line is classified, whether or not
   * it came from the catalogue. It is seeded from the product's own category but
   * kept as a snapshot, so the two are free to diverge.
   */
  categoryId: string;
  name: string;
  quantity: number;
  /**
   * Price for one unit, in minor units of the transaction's currency.
   */
  unitPriceMinor: number;
  /**
   * Every discount on this line, in the order the receipt prints them.
   *
   * The order is the answer, not a display preference: they **cascade**, each one
   * off what the ones above it left behind. 55_000 at 20% and then 5% comes to
   * 11_000 and 2_200, because the second rate reads against the 44_000 the first
   * left — swapping the two changes both figures.
   *
   * The API derives `discountMinor` and `lineTotalMinor` from them, the same way
   * it already owns the line total. Absent means no discount; on an update, an
   * empty array clears the ones that are there while absent leaves them alone.
   */
  discounts?: Array<TransactionItemDiscountDto>;
};

export type UpdateTransactionItemDto = {
  /**
   * Optional link to the catalogue. A line typed by hand has none and needs no
   * product code at all — promoting it to master data is a separate, deliberate step.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  productId?: string | null;
  /**
   * Required, unlike the product link: every line is classified, whether or not
   * it came from the catalogue. It is seeded from the product's own category but
   * kept as a snapshot, so the two are free to diverge.
   */
  categoryId?: string;
  name?: string;
  quantity?: number;
  /**
   * Price for one unit, in minor units of the transaction's currency.
   */
  unitPriceMinor?: number;
  /**
   * Every discount on this line, in the order the receipt prints them.
   *
   * The order is the answer, not a display preference: they **cascade**, each one
   * off what the ones above it left behind. 55_000 at 20% and then 5% comes to
   * 11_000 and 2_200, because the second rate reads against the 44_000 the first
   * left — swapping the two changes both figures.
   *
   * The API derives `discountMinor` and `lineTotalMinor` from them, the same way
   * it already owns the line total. Absent means no discount; on an update, an
   * empty array clears the ones that are there while absent leaves them alone.
   */
  discounts?: Array<TransactionItemDiscountDto>;
};

export type CreateSettlementDto = {
  /**
   * The wallet that owed a share of this receipt and has now paid it back.
   */
  owedAccountId: string;
  /**
   * When the money moved. Defaults to now, which is also when the rows are posted.
   */
  settledAt?: string;
};

export type OutstandingReceiptResponse = {
  transactionId: string;
  /**
   * What the receipt was described as, if anything.
   */
  description: string | null;
  /**
   * Where it was paid. The client names a receipt by its description and falls back to this, the same order the transaction list uses.
   */
  merchantName: string | null;
  occurredAt: string;
  /**
   * This account's share of this one receipt, in minor units.
   */
  owedMinor: number;
};

export type OutstandingReimbursementResponse = {
  /**
   * The wallet that owes.
   */
  owedAccountId: string;
  owedAccountName: string;
  /**
   * The wallet that fronted the money.
   */
  paidByAccountId: string;
  paidByAccountName: string;
  /**
   * ISO 4217 code of the receipts, which is the paying account's.
   */
  currency: string;
  /**
   * Sum of the unreimbursed shares, in minor units of `currency`. Derived on every read, so editing a receipt moves it.
   */
  owedMinor: number;
  /**
   * How many receipts the figure is made of.
   */
  receiptCount: number;
  /**
   * When the oldest of them was paid.
   */
  oldestOccurredAt: string;
  /**
   * Newest first.
   */
  receipts: Array<OutstandingReceiptResponse>;
};

export type OutstandingCurrencyTotalResponse = {
  /**
   * ISO 4217 code.
   */
  currency: string;
  /**
   * Integer minor units of `currency`.
   */
  owedMinor: number;
};

export type OutstandingReimbursementsResponse = {
  /**
   * Largest debt first.
   */
  data: Array<OutstandingReimbursementResponse>;
  totalsByCurrency: Array<OutstandingCurrencyTotalResponse>;
};

export type ScanReceiptDto = {
  /**
   * The account this receipt will be paid from.
   */
  accountId: string;
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp';
  /**
   * The photo, base64 encoded, without a data: URL prefix.
   */
  imageBase64: string;
};

export type ReceiptDraftMerchantResponse = {
  /**
   * The matched merchant, or null when nothing in the catalogue matched.
   */
  id?: string | null;
  /**
   * The merchant's catalogue name when matched, otherwise the name as printed.
   */
  name?: string | null;
};

export type ReceiptDraftDiscountResponse = {
  name?: string | null;
  /**
   * Basis points off the running remainder (5% is 500).
   */
  basisPoints?: number | null;
  /**
   * A lump sum off the line, in minor units, when the receipt printed one.
   */
  amountMinor?: number | null;
};

export type ReceiptDraftLineResponse = {
  /**
   * The catalogue product this line matched, or null when it is new.
   */
  productId?: string | null;
  /**
   * The matched product's category. Null when unmatched — the reviewer picks one.
   */
  categoryId?: string | null;
  categoryName?: string | null;
  name: string;
  quantity: number;
  /**
   * Per unit, in the account's minor units.
   */
  unitPriceMinor: number;
  /**
   * Every discount printed under this line, in the order they cascade.
   */
  discounts: Array<ReceiptDraftDiscountResponse>;
  /**
   * What the whole cascade comes to as one rate (24% is 2400).
   */
  discountBasisPoints: number;
  /**
   * quantity × unitPriceMinor less the discounts, derived the same way a saved line is.
   */
  lineTotalMinor: number;
};

export type ReceiptDraftChargeResponse = {
  name: string;
  /**
   * Basis points (11% is 1100), when the receipt printed a rate.
   */
  percentBasisPoints?: number | null;
  amountMinor: number;
};

export type ReceiptDraftResponse = {
  /**
   * The account the amounts below were scaled for.
   */
  accountId: string;
  /**
   * The account's currency. Every *Minor field is in it.
   */
  currency: string;
  merchant: ReceiptDraftMerchantResponse;
  /**
   * The printed date at UTC midnight, or null when the receipt showed none.
   */
  occurredAt?: string | null;
  /**
   * Seeded from the merchant name, so the transaction row reads as something.
   */
  description?: string | null;
  lines: Array<ReceiptDraftLineResponse>;
  charges: Array<ReceiptDraftChargeResponse>;
  /**
   * The grand total as printed on the receipt. Null when it was unreadable.
   */
  printedTotalMinor?: number | null;
  /**
   * The sum of the lines and charges above. Disagreement means something was misread.
   */
  derivedTotalMinor: number;
};

export type CreateReceiptDto = {
  accountId: string;
  merchantId?: string | null;
  occurredAt: string;
  description?: string;
  notes?: string;
  /**
   * Reuses the line shape the per-item endpoints already validate.
   */
  items: Array<CreateTransactionItemDto>;
  charges?: Array<CreateTransactionChargeDto>;
};

export type AuthRegisterData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type AuthRegisterResponses = {
  201: AuthTokensResponse;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type AuthLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type AuthLoginResponses = {
  200: AuthTokensResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
  body: RefreshDto;
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type AuthRefreshResponses = {
  200: AuthTokensResponse;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
  body: RefreshDto;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type AuthLogoutResponses = {
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type AuthMeResponses = {
  200: UserResponse;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthCheckResponses = {
  200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type AccountsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
    /**
     * Free-text filter, matched case-insensitively.
     */
    search?: string;
    includeArchived?: boolean;
  };
  url: '/accounts';
};

export type AccountsFindAllResponses = {
  200: PaginatedAccountsResponse;
};

export type AccountsFindAllResponse = AccountsFindAllResponses[keyof AccountsFindAllResponses];

export type AccountsCreateData = {
  body: CreateAccountDto;
  path?: never;
  query?: never;
  url: '/accounts';
};

export type AccountsCreateResponses = {
  201: AccountResponse;
};

export type AccountsCreateResponse = AccountsCreateResponses[keyof AccountsCreateResponses];

export type AccountsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}';
};

export type AccountsRemoveResponses = {
  204: void;
};

export type AccountsRemoveResponse = AccountsRemoveResponses[keyof AccountsRemoveResponses];

export type AccountsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}';
};

export type AccountsFindOneResponses = {
  200: AccountResponse;
};

export type AccountsFindOneResponse = AccountsFindOneResponses[keyof AccountsFindOneResponses];

export type AccountsUpdateData = {
  body: UpdateAccountDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}';
};

export type AccountsUpdateResponses = {
  200: AccountResponse;
};

export type AccountsUpdateResponse = AccountsUpdateResponses[keyof AccountsUpdateResponses];

export type AccountsGetBalanceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}/balance';
};

export type AccountsGetBalanceResponses = {
  200: AccountBalanceResponse;
};

export type AccountsGetBalanceResponse =
  AccountsGetBalanceResponses[keyof AccountsGetBalanceResponses];

export type CategoriesFindAllData = {
  body?: never;
  path?: never;
  query?: {
    kind?: CategoryKind;
    accountId?: string;
  };
  url: '/categories';
};

export type CategoriesFindAllResponses = {
  200: Array<CategoryResponse>;
};

export type CategoriesFindAllResponse =
  CategoriesFindAllResponses[keyof CategoriesFindAllResponses];

export type CategoriesCreateData = {
  body: CreateCategoryDto;
  path?: never;
  query?: never;
  url: '/categories';
};

export type CategoriesCreateResponses = {
  201: CategoryResponse;
};

export type CategoriesCreateResponse = CategoriesCreateResponses[keyof CategoriesCreateResponses];

export type CategoriesRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/categories/{id}';
};

export type CategoriesRemoveResponses = {
  204: void;
};

export type CategoriesRemoveResponse = CategoriesRemoveResponses[keyof CategoriesRemoveResponses];

export type CategoriesFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/categories/{id}';
};

export type CategoriesFindOneResponses = {
  200: CategoryResponse;
};

export type CategoriesFindOneResponse =
  CategoriesFindOneResponses[keyof CategoriesFindOneResponses];

export type CategoriesUpdateData = {
  body: UpdateCategoryDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/categories/{id}';
};

export type CategoriesUpdateResponses = {
  200: CategoryResponse;
};

export type CategoriesUpdateResponse = CategoriesUpdateResponses[keyof CategoriesUpdateResponses];

export type MerchantsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
  };
  url: '/merchants';
};

export type MerchantsFindAllResponses = {
  200: Array<MerchantResponse>;
};

export type MerchantsFindAllResponse = MerchantsFindAllResponses[keyof MerchantsFindAllResponses];

export type MerchantsCreateData = {
  body: CreateMerchantDto;
  path?: never;
  query?: never;
  url: '/merchants';
};

export type MerchantsCreateResponses = {
  201: MerchantResponse;
};

export type MerchantsCreateResponse = MerchantsCreateResponses[keyof MerchantsCreateResponses];

export type MerchantsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/merchants/{id}';
};

export type MerchantsRemoveResponses = {
  204: void;
};

export type MerchantsRemoveResponse = MerchantsRemoveResponses[keyof MerchantsRemoveResponses];

export type MerchantsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/merchants/{id}';
};

export type MerchantsFindOneResponses = {
  200: MerchantResponse;
};

export type MerchantsFindOneResponse = MerchantsFindOneResponses[keyof MerchantsFindOneResponses];

export type MerchantsUpdateData = {
  body: UpdateMerchantDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/merchants/{id}';
};

export type MerchantsUpdateResponses = {
  200: MerchantResponse;
};

export type MerchantsUpdateResponse = MerchantsUpdateResponses[keyof MerchantsUpdateResponses];

export type ProductsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    merchantId?: string;
    search?: string;
  };
  url: '/products';
};

export type ProductsFindAllResponses = {
  200: Array<ProductResponse>;
};

export type ProductsFindAllResponse = ProductsFindAllResponses[keyof ProductsFindAllResponses];

export type ProductsCreateData = {
  body: CreateProductDto;
  path?: never;
  query?: never;
  url: '/products';
};

export type ProductsCreateResponses = {
  201: ProductResponse;
};

export type ProductsCreateResponse = ProductsCreateResponses[keyof ProductsCreateResponses];

export type ProductsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/products/{id}';
};

export type ProductsRemoveResponses = {
  204: void;
};

export type ProductsRemoveResponse = ProductsRemoveResponses[keyof ProductsRemoveResponses];

export type ProductsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/products/{id}';
};

export type ProductsFindOneResponses = {
  200: ProductResponse;
};

export type ProductsFindOneResponse = ProductsFindOneResponses[keyof ProductsFindOneResponses];

export type ProductsUpdateData = {
  body: UpdateProductDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/products/{id}';
};

export type ProductsUpdateResponses = {
  200: ProductResponse;
};

export type ProductsUpdateResponse = ProductsUpdateResponses[keyof ProductsUpdateResponses];

export type TransactionsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
    /**
     * Free-text filter, matched case-insensitively.
     */
    search?: string;
    accountId?: string;
    categoryId?: string;
    merchantId?: string;
    type?: TransactionType;
    /**
     * Inclusive lower bound on occurredAt.
     */
    from?: string;
    /**
     * Exclusive upper bound on occurredAt.
     */
    to?: string;
  };
  url: '/transactions';
};

export type TransactionsFindAllResponses = {
  200: PaginatedTransactionsResponse;
};

export type TransactionsFindAllResponse =
  TransactionsFindAllResponses[keyof TransactionsFindAllResponses];

export type TransactionsCreateData = {
  body: CreateTransactionDto;
  path?: never;
  query?: never;
  url: '/transactions';
};

export type TransactionsCreateResponses = {
  201: TransactionResponse;
};

export type TransactionsCreateResponse =
  TransactionsCreateResponses[keyof TransactionsCreateResponses];

export type TransactionsSummariseData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Inclusive lower bound. Defaults to the start of the current month.
     */
    from?: string;
    /**
     * Exclusive upper bound. Defaults to the start of next month.
     */
    to?: string;
    /**
     * Restrict the summary to one account.
     */
    accountId?: string;
  };
  url: '/transactions/summary';
};

export type TransactionsSummariseResponses = {
  200: TransactionsSummaryResponse;
};

export type TransactionsSummariseResponse =
  TransactionsSummariseResponses[keyof TransactionsSummariseResponses];

export type TransactionsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/transactions/{id}';
};

export type TransactionsRemoveResponses = {
  204: void;
};

export type TransactionsRemoveResponse =
  TransactionsRemoveResponses[keyof TransactionsRemoveResponses];

export type TransactionsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/transactions/{id}';
};

export type TransactionsFindOneResponses = {
  200: TransactionResponse;
};

export type TransactionsFindOneResponse =
  TransactionsFindOneResponses[keyof TransactionsFindOneResponses];

export type TransactionsUpdateData = {
  body: UpdateTransactionDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/transactions/{id}';
};

export type TransactionsUpdateResponses = {
  200: TransactionResponse;
};

export type TransactionsUpdateResponse =
  TransactionsUpdateResponses[keyof TransactionsUpdateResponses];

export type TransactionItemsCreateData = {
  body: CreateTransactionItemDto;
  path: {
    transactionId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/items';
};

export type TransactionItemsCreateResponses = {
  201: TransactionResponse;
};

export type TransactionItemsCreateResponse =
  TransactionItemsCreateResponses[keyof TransactionItemsCreateResponses];

export type TransactionItemsRemoveData = {
  body?: never;
  path: {
    transactionId: string;
    itemId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/items/{itemId}';
};

export type TransactionItemsRemoveResponses = {
  200: TransactionResponse;
};

export type TransactionItemsRemoveResponse =
  TransactionItemsRemoveResponses[keyof TransactionItemsRemoveResponses];

export type TransactionItemsUpdateData = {
  body: UpdateTransactionItemDto;
  path: {
    transactionId: string;
    itemId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/items/{itemId}';
};

export type TransactionItemsUpdateResponses = {
  200: TransactionResponse;
};

export type TransactionItemsUpdateResponse =
  TransactionItemsUpdateResponses[keyof TransactionItemsUpdateResponses];

export type TransactionSettlementsSettleData = {
  body: CreateSettlementDto;
  path: {
    transactionId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/settlements';
};

export type TransactionSettlementsSettleResponses = {
  201: TransactionResponse;
};

export type TransactionSettlementsSettleResponse =
  TransactionSettlementsSettleResponses[keyof TransactionSettlementsSettleResponses];

export type TransactionSettlementsUnsettleData = {
  body?: never;
  path: {
    transactionId: string;
    owedAccountId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/settlements/{owedAccountId}';
};

export type TransactionSettlementsUnsettleResponses = {
  200: TransactionResponse;
};

export type TransactionSettlementsUnsettleResponse =
  TransactionSettlementsUnsettleResponses[keyof TransactionSettlementsUnsettleResponses];

export type ReimbursementsFindOutstandingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/reimbursements/outstanding';
};

export type ReimbursementsFindOutstandingResponses = {
  200: OutstandingReimbursementsResponse;
};

export type ReimbursementsFindOutstandingResponse =
  ReimbursementsFindOutstandingResponses[keyof ReimbursementsFindOutstandingResponses];

export type ReceiptsScanData = {
  body: ScanReceiptDto;
  path?: never;
  query?: never;
  url: '/receipts/scan';
};

export type ReceiptsScanResponses = {
  200: ReceiptDraftResponse;
};

export type ReceiptsScanResponse = ReceiptsScanResponses[keyof ReceiptsScanResponses];

export type ReceiptsCreateData = {
  body: CreateReceiptDto;
  path?: never;
  query?: never;
  url: '/receipts';
};

export type ReceiptsCreateResponses = {
  201: TransactionResponse;
};

export type ReceiptsCreateResponse = ReceiptsCreateResponses[keyof ReceiptsCreateResponses];
