// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type RegisterDto = {
  email: string;
  /**
   * Stored only as an argon2 hash.
   */
  password: string;
  displayName?: string;
  /**
   * Shared invite code. Registration is closed without it.
   */
  inviteCode: string;
};

export type UserResponse = {
  id: string;
  email: string;
  displayName?: string | null;
  createdAt: string;
};

export type AuthTokensResponse = {
  /**
   * Short-lived bearer token for the Authorization header.
   */
  accessToken: string;
  /**
   * Opaque token, exchanged at /auth/refresh. Rotated on every use.
   */
  refreshToken: string;
  /**
   * Seconds until the access token expires.
   */
  expiresIn: number;
  user: UserResponse;
};

export type LoginDto = {
  email: string;
  password: string;
};

export type RefreshDto = {
  /**
   * The refresh token from the last token response.
   */
  refreshToken: string;
};

export type HealthResponse = {
  status: 'ok' | 'degraded';
  database: 'up' | 'down';
  /**
   * Process uptime in seconds.
   */
  uptime: number;
};

export const AccountType = {
  CASH: 'CASH',
  BANK: 'BANK',
  EWALLET: 'EWALLET',
  CREDIT_CARD: 'CREDIT_CARD',
  INVESTMENT: 'INVESTMENT',
} as const;

export type AccountType = (typeof AccountType)[keyof typeof AccountType];

export type AccountResponse = {
  id: string;
  name: string;
  type: AccountType;
  /**
   * ISO 4217 code.
   */
  currency: string;
  openingBalanceMinor: number;
  /**
   * Categories paid from this account. Deleting it leaves them unassigned.
   */
  categoryCount: number;
  /**
   * Transactions posted here. Deleting the account deletes them.
   */
  transactionCount: number;
  archivedAt?: string | null;
  createdAt: string;
  updatedAt: string;
};

export type AccountBalanceResponse = {
  accountId: string;
  currency: string;
  openingBalanceMinor: number;
  incomeMinor: number;
  expenseMinor: number;
  /**
   * openingBalanceMinor + incomeMinor - expenseMinor
   */
  balanceMinor: number;
};

export type CreateAccountDto = {
  name: string;
  type: AccountType;
  /**
   * ISO 4217 code.
   */
  currency?: string;
  /**
   * Balance before the first tracked transaction, in minor units.
   */
  openingBalanceMinor?: number;
};

export type UpdateAccountDto = {
  name?: string;
  type?: AccountType;
  /**
   * ISO 4217 code.
   */
  currency?: string;
  /**
   * Balance before the first tracked transaction, in minor units.
   */
  openingBalanceMinor?: number;
  /**
   * Archive (true) or restore (false) the account.
   */
  archived?: boolean;
};

export const CategoryKind = { INCOME: 'INCOME', EXPENSE: 'EXPENSE' } as const;

export type CategoryKind = (typeof CategoryKind)[keyof typeof CategoryKind];

export type CategoryResponse = {
  id: string;
  name: string;
  /**
   * The account this category is paid from; null when it is unassigned.
   */
  accountId?: string | null;
  /**
   * Denormalised so a category list need not also fetch accounts.
   */
  accountName?: string | null;
  kind: CategoryKind;
  color?: string | null;
  /**
   * Receipt lines filed under this category. Deleting it leaves them uncategorised.
   */
  transactionItemCount: number;
  /**
   * Catalogue products classified by this category.
   */
  productCount: number;
  createdAt: string;
  updatedAt: string;
};

export type CreateCategoryDto = {
  name: string;
  /**
   * The account this category is paid from. Optional — an unassigned category can
   * be used on any account.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  accountId?: string | null;
  kind: CategoryKind;
  /**
   * Hex swatch used by the UI.
   */
  color?: string;
};

export type UpdateCategoryDto = {
  name?: string;
  /**
   * The account this category is paid from. Optional — an unassigned category can
   * be used on any account.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  accountId?: string | null;
  kind?: CategoryKind;
  /**
   * Hex swatch used by the UI.
   */
  color?: string;
};

export type MerchantResponse = {
  id: string;
  name: string;
  /**
   * How many transactions point at this merchant. Deleting it detaches them, not deletes them.
   */
  transactionCount: number;
  /**
   * How many products this merchant sells. Deleting it deletes them too.
   */
  productCount: number;
  createdAt: string;
  updatedAt: string;
};

export type CreateMerchantDto = {
  name: string;
};

export type UpdateMerchantDto = {
  name?: string;
};

export type CategorySummaryResponse = {
  id: string;
  name: string;
  kind: CategoryKind;
  color?: string | null;
};

export type ProductResponse = {
  id: string;
  merchantId: string;
  /**
   * Denormalised so a product list need not also fetch merchants.
   */
  merchantName: string;
  /**
   * Only null for rows that predate categorised products.
   */
  category?: CategorySummaryResponse | null;
  code: string;
  name: string;
  /**
   * Price last paid, in minor units of `currency`.
   */
  lastPriceMinor: number;
  /**
   * ISO 4217 code. Always IDR for now.
   */
  currency: string;
  createdAt: string;
  updatedAt: string;
};

export type CreateProductDto = {
  /**
   * The merchant that sells this product.
   */
  merchantId: string;
  /**
   * Must be an EXPENSE category.
   */
  categoryId: string;
  /**
   * The merchant's own SKU. Unique within it.
   */
  code: string;
  name: string;
  /**
   * Price last paid, in IDR minor units.
   */
  lastPriceMinor: number;
};

export type UpdateProductDto = {
  /**
   * The merchant that sells this product.
   */
  merchantId?: string;
  /**
   * Must be an EXPENSE category.
   */
  categoryId?: string;
  /**
   * The merchant's own SKU. Unique within it.
   */
  code?: string;
  name?: string;
  /**
   * Price last paid, in IDR minor units.
   */
  lastPriceMinor?: number;
};

export const TransactionType = { INCOME: 'INCOME', EXPENSE: 'EXPENSE' } as const;

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType];

export type TransactionAccountResponse = {
  id: string;
  name: string;
  type: AccountType;
};

export type TransactionMerchantResponse = {
  id: string;
  name: string;
};

export type TransactionItemProductResponse = {
  id: string;
  code: string;
  name: string;
};

export type TransactionItemResponse = {
  id: string;
  name: string;
  quantity: number;
  unitPriceMinor: number;
  /**
   * quantity × unitPriceMinor.
   */
  lineTotalMinor: number;
  /**
   * Order on the receipt.
   */
  position: number;
  /**
   * Null for a line typed by hand that is not in the catalogue.
   */
  product?: TransactionItemProductResponse | null;
  /**
   * Only null for rows that predate categorised lines.
   */
  category?: CategorySummaryResponse | null;
  createdAt: string;
  updatedAt: string;
};

export type TransactionResponse = {
  id: string;
  type: TransactionType;
  /**
   * Positive integer in minor units; sign comes from `type`. On an EXPENSE it is derived — the sum of `items[].lineTotalMinor`, so a receipt with nothing itemised yet reads zero. On an INCOME it is the figure that was entered, and there are no items.
   */
  amountMinor: number;
  currency: string;
  occurredAt: string;
  description?: string | null;
  notes?: string | null;
  account: TransactionAccountResponse;
  merchant?: TransactionMerchantResponse | null;
  /**
   * How an INCOME transaction is classified, since it has no items to carry a category. Always null on an EXPENSE, which is categorised line by line in `items[].category`.
   */
  category?: CategorySummaryResponse | null;
  /**
   * What was bought, in receipt order. Empty until an expense is itemised, and always empty on income — the API refuses to write items on an INCOME transaction.
   */
  items: Array<TransactionItemResponse>;
  createdAt: string;
  updatedAt: string;
};

export type PaginatedTransactionsResponse = {
  /**
   * Total rows matching the filter, ignoring limit/offset.
   */
  total: number;
  limit: number;
  offset: number;
  data: Array<TransactionResponse>;
};

export type CategoryTotalResponse = {
  categoryId?: string | null;
  categoryName: string;
  color?: string | null;
  type: TransactionType;
  totalMinor: number;
};

export type TransactionsSummaryResponse = {
  from: string;
  to: string;
  incomeMinor: number;
  expenseMinor: number;
  /**
   * incomeMinor - expenseMinor
   */
  netMinor: number;
  byCategory: Array<CategoryTotalResponse>;
};

export type CreateTransactionDto = {
  accountId: string;
  /**
   * Optional. A transaction with no merchant is perfectly valid.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  merchantId?: string | null;
  type: TransactionType;
  /**
   * Required on INCOME, rejected on EXPENSE. Minor units of the account's currency.
   */
  amountMinor?: number;
  /**
   * Required on INCOME and must be an INCOME category. Rejected on EXPENSE.
   */
  categoryId?: string | null;
  occurredAt: string;
  description?: string;
  notes?: string;
};

export type UpdateTransactionDto = {
  accountId?: string;
  /**
   * Optional. A transaction with no merchant is perfectly valid.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  merchantId?: string | null;
  type?: TransactionType;
  /**
   * Required on INCOME, rejected on EXPENSE. Minor units of the account's currency.
   */
  amountMinor?: number;
  /**
   * Required on INCOME and must be an INCOME category. Rejected on EXPENSE.
   */
  categoryId?: string | null;
  occurredAt?: string;
  description?: string;
  notes?: string;
};

export type CreateTransactionItemDto = {
  /**
   * Optional link to the catalogue. A line typed by hand has none and needs no
   * product code at all — promoting it to master data is a separate, deliberate step.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  productId?: string | null;
  /**
   * Required, unlike the product link: every line is classified, whether or not
   * it came from the catalogue. It is seeded from the product's own category but
   * kept as a snapshot, so the two are free to diverge.
   */
  categoryId: string;
  name: string;
  quantity: number;
  /**
   * Price for one unit, in minor units of the transaction's currency.
   */
  unitPriceMinor: number;
};

export type UpdateTransactionItemDto = {
  /**
   * Optional link to the catalogue. A line typed by hand has none and needs no
   * product code at all — promoting it to master data is a separate, deliberate step.
   *
   * `null` and absent are not the same thing and must stay distinguishable all the
   * way to Prisma: absent means "leave the link alone", `null` means "clear it".
   */
  productId?: string | null;
  /**
   * Required, unlike the product link: every line is classified, whether or not
   * it came from the catalogue. It is seeded from the product's own category but
   * kept as a snapshot, so the two are free to diverge.
   */
  categoryId?: string;
  name?: string;
  quantity?: number;
  /**
   * Price for one unit, in minor units of the transaction's currency.
   */
  unitPriceMinor?: number;
};

export type AuthRegisterData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type AuthRegisterResponses = {
  201: AuthTokensResponse;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type AuthLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type AuthLoginResponses = {
  200: AuthTokensResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
  body: RefreshDto;
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type AuthRefreshResponses = {
  200: AuthTokensResponse;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
  body: RefreshDto;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type AuthLogoutResponses = {
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type AuthMeResponses = {
  200: UserResponse;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthCheckResponses = {
  200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type AccountsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    includeArchived?: boolean;
  };
  url: '/accounts';
};

export type AccountsFindAllResponses = {
  200: Array<AccountResponse>;
};

export type AccountsFindAllResponse = AccountsFindAllResponses[keyof AccountsFindAllResponses];

export type AccountsCreateData = {
  body: CreateAccountDto;
  path?: never;
  query?: never;
  url: '/accounts';
};

export type AccountsCreateResponses = {
  201: AccountResponse;
};

export type AccountsCreateResponse = AccountsCreateResponses[keyof AccountsCreateResponses];

export type AccountsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}';
};

export type AccountsRemoveResponses = {
  204: void;
};

export type AccountsRemoveResponse = AccountsRemoveResponses[keyof AccountsRemoveResponses];

export type AccountsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}';
};

export type AccountsFindOneResponses = {
  200: AccountResponse;
};

export type AccountsFindOneResponse = AccountsFindOneResponses[keyof AccountsFindOneResponses];

export type AccountsUpdateData = {
  body: UpdateAccountDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}';
};

export type AccountsUpdateResponses = {
  200: AccountResponse;
};

export type AccountsUpdateResponse = AccountsUpdateResponses[keyof AccountsUpdateResponses];

export type AccountsGetBalanceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/accounts/{id}/balance';
};

export type AccountsGetBalanceResponses = {
  200: AccountBalanceResponse;
};

export type AccountsGetBalanceResponse =
  AccountsGetBalanceResponses[keyof AccountsGetBalanceResponses];

export type CategoriesFindAllData = {
  body?: never;
  path?: never;
  query?: {
    kind?: CategoryKind;
    accountId?: string;
  };
  url: '/categories';
};

export type CategoriesFindAllResponses = {
  200: Array<CategoryResponse>;
};

export type CategoriesFindAllResponse =
  CategoriesFindAllResponses[keyof CategoriesFindAllResponses];

export type CategoriesCreateData = {
  body: CreateCategoryDto;
  path?: never;
  query?: never;
  url: '/categories';
};

export type CategoriesCreateResponses = {
  201: CategoryResponse;
};

export type CategoriesCreateResponse = CategoriesCreateResponses[keyof CategoriesCreateResponses];

export type CategoriesRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/categories/{id}';
};

export type CategoriesRemoveResponses = {
  204: void;
};

export type CategoriesRemoveResponse = CategoriesRemoveResponses[keyof CategoriesRemoveResponses];

export type CategoriesFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/categories/{id}';
};

export type CategoriesFindOneResponses = {
  200: CategoryResponse;
};

export type CategoriesFindOneResponse =
  CategoriesFindOneResponses[keyof CategoriesFindOneResponses];

export type CategoriesUpdateData = {
  body: UpdateCategoryDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/categories/{id}';
};

export type CategoriesUpdateResponses = {
  200: CategoryResponse;
};

export type CategoriesUpdateResponse = CategoriesUpdateResponses[keyof CategoriesUpdateResponses];

export type MerchantsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
  };
  url: '/merchants';
};

export type MerchantsFindAllResponses = {
  200: Array<MerchantResponse>;
};

export type MerchantsFindAllResponse = MerchantsFindAllResponses[keyof MerchantsFindAllResponses];

export type MerchantsCreateData = {
  body: CreateMerchantDto;
  path?: never;
  query?: never;
  url: '/merchants';
};

export type MerchantsCreateResponses = {
  201: MerchantResponse;
};

export type MerchantsCreateResponse = MerchantsCreateResponses[keyof MerchantsCreateResponses];

export type MerchantsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/merchants/{id}';
};

export type MerchantsRemoveResponses = {
  204: void;
};

export type MerchantsRemoveResponse = MerchantsRemoveResponses[keyof MerchantsRemoveResponses];

export type MerchantsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/merchants/{id}';
};

export type MerchantsFindOneResponses = {
  200: MerchantResponse;
};

export type MerchantsFindOneResponse = MerchantsFindOneResponses[keyof MerchantsFindOneResponses];

export type MerchantsUpdateData = {
  body: UpdateMerchantDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/merchants/{id}';
};

export type MerchantsUpdateResponses = {
  200: MerchantResponse;
};

export type MerchantsUpdateResponse = MerchantsUpdateResponses[keyof MerchantsUpdateResponses];

export type ProductsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    merchantId?: string;
    search?: string;
  };
  url: '/products';
};

export type ProductsFindAllResponses = {
  200: Array<ProductResponse>;
};

export type ProductsFindAllResponse = ProductsFindAllResponses[keyof ProductsFindAllResponses];

export type ProductsCreateData = {
  body: CreateProductDto;
  path?: never;
  query?: never;
  url: '/products';
};

export type ProductsCreateResponses = {
  201: ProductResponse;
};

export type ProductsCreateResponse = ProductsCreateResponses[keyof ProductsCreateResponses];

export type ProductsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/products/{id}';
};

export type ProductsRemoveResponses = {
  204: void;
};

export type ProductsRemoveResponse = ProductsRemoveResponses[keyof ProductsRemoveResponses];

export type ProductsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/products/{id}';
};

export type ProductsFindOneResponses = {
  200: ProductResponse;
};

export type ProductsFindOneResponse = ProductsFindOneResponses[keyof ProductsFindOneResponses];

export type ProductsUpdateData = {
  body: UpdateProductDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/products/{id}';
};

export type ProductsUpdateResponses = {
  200: ProductResponse;
};

export type ProductsUpdateResponse = ProductsUpdateResponses[keyof ProductsUpdateResponses];

export type TransactionsFindAllData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
    /**
     * Free-text filter, matched case-insensitively.
     */
    search?: string;
    accountId?: string;
    categoryId?: string;
    merchantId?: string;
    type?: TransactionType;
    /**
     * Inclusive lower bound on occurredAt.
     */
    from?: string;
    /**
     * Exclusive upper bound on occurredAt.
     */
    to?: string;
  };
  url: '/transactions';
};

export type TransactionsFindAllResponses = {
  200: PaginatedTransactionsResponse;
};

export type TransactionsFindAllResponse =
  TransactionsFindAllResponses[keyof TransactionsFindAllResponses];

export type TransactionsCreateData = {
  body: CreateTransactionDto;
  path?: never;
  query?: never;
  url: '/transactions';
};

export type TransactionsCreateResponses = {
  201: TransactionResponse;
};

export type TransactionsCreateResponse =
  TransactionsCreateResponses[keyof TransactionsCreateResponses];

export type TransactionsSummariseData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Inclusive lower bound. Defaults to the start of the current month.
     */
    from?: string;
    /**
     * Exclusive upper bound. Defaults to the start of next month.
     */
    to?: string;
    /**
     * Restrict the summary to one account.
     */
    accountId?: string;
  };
  url: '/transactions/summary';
};

export type TransactionsSummariseResponses = {
  200: TransactionsSummaryResponse;
};

export type TransactionsSummariseResponse =
  TransactionsSummariseResponses[keyof TransactionsSummariseResponses];

export type TransactionsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/transactions/{id}';
};

export type TransactionsRemoveResponses = {
  204: void;
};

export type TransactionsRemoveResponse =
  TransactionsRemoveResponses[keyof TransactionsRemoveResponses];

export type TransactionsFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/transactions/{id}';
};

export type TransactionsFindOneResponses = {
  200: TransactionResponse;
};

export type TransactionsFindOneResponse =
  TransactionsFindOneResponses[keyof TransactionsFindOneResponses];

export type TransactionsUpdateData = {
  body: UpdateTransactionDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/transactions/{id}';
};

export type TransactionsUpdateResponses = {
  200: TransactionResponse;
};

export type TransactionsUpdateResponse =
  TransactionsUpdateResponses[keyof TransactionsUpdateResponses];

export type TransactionItemsCreateData = {
  body: CreateTransactionItemDto;
  path: {
    transactionId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/items';
};

export type TransactionItemsCreateResponses = {
  201: TransactionResponse;
};

export type TransactionItemsCreateResponse =
  TransactionItemsCreateResponses[keyof TransactionItemsCreateResponses];

export type TransactionItemsRemoveData = {
  body?: never;
  path: {
    transactionId: string;
    itemId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/items/{itemId}';
};

export type TransactionItemsRemoveResponses = {
  200: TransactionResponse;
};

export type TransactionItemsRemoveResponse =
  TransactionItemsRemoveResponses[keyof TransactionItemsRemoveResponses];

export type TransactionItemsUpdateData = {
  body: UpdateTransactionItemDto;
  path: {
    transactionId: string;
    itemId: string;
  };
  query?: never;
  url: '/transactions/{transactionId}/items/{itemId}';
};

export type TransactionItemsUpdateResponses = {
  200: TransactionResponse;
};

export type TransactionItemsUpdateResponse =
  TransactionItemsUpdateResponses[keyof TransactionItemsUpdateResponses];
